"""rename metadata columns

Revision ID: cc273f2d7b2f
Revises: fbc4b7975eff
Create Date: 2026-09-01 20:04:15.103128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cc273f2d7b2f'
down_revision: Union[str, Sequence[str], None] = 'fbc4b7975eff'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('audit_logs', sa.Column('change_data', sa.JSON(), nullable=True))
    op.drop_column('audit_logs', 'metadata')
    op.drop_constraint(op.f('refresh_tokens_replaced_by_id_fkey'), 'refresh_tokens', type_='foreignkey')
    op.create_foreign_key(None, 'refresh_tokens', 'refresh_tokens', ['replaced_by_id'], ['id'])
    op.add_column('security_logs', sa.Column('log_metadata', sa.JSON(), nullable=True))
    op.drop_column('security_logs', 'metadata')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('security_logs', sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('security_logs', 'log_metadata')
    op.drop_constraint(None, 'refresh_tokens', type_='foreignkey')
    op.create_foreign_key(op.f('refresh_tokens_replaced_by_id_fkey'), 'refresh_tokens', 'refresh_tokens', ['replaced_by_id'], ['id'], ondelete='SET NULL')
    op.add_column('audit_logs', sa.Column('metadata', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('audit_logs', 'change_data')
    # ### end Alembic commands ###
